# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from libs import rpc_pb2 as rpc__pb2


class ReProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Encrypt = channel.unary_unary(
        '/nucypher.ReProxy/Encrypt',
        request_serializer=rpc__pb2.EncryptRequest.SerializeToString,
        response_deserializer=rpc__pb2.EncryptReply.FromString,
        )
    self.Decrypt = channel.unary_unary(
        '/nucypher.ReProxy/Decrypt',
        request_serializer=rpc__pb2.DecryptRequest.SerializeToString,
        response_deserializer=rpc__pb2.DecryptReply.FromString,
        )
    self.GetKFlags = channel.unary_unary(
        '/nucypher.ReProxy/GetKFlags',
        request_serializer=rpc__pb2.GetKFlagsRequest.SerializeToString,
        response_deserializer=rpc__pb2.GetKFlagsReply.FromString,
        )
    self.Capsule = channel.unary_unary(
        '/nucypher.ReProxy/Capsule',
        request_serializer=rpc__pb2.CapsuleRequest.SerializeToString,
        response_deserializer=rpc__pb2.CapsuleReply.FromString,
        )


class ReProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Encrypt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Decrypt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKFlags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Capsule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Encrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Encrypt,
          request_deserializer=rpc__pb2.EncryptRequest.FromString,
          response_serializer=rpc__pb2.EncryptReply.SerializeToString,
      ),
      'Decrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Decrypt,
          request_deserializer=rpc__pb2.DecryptRequest.FromString,
          response_serializer=rpc__pb2.DecryptReply.SerializeToString,
      ),
      'GetKFlags': grpc.unary_unary_rpc_method_handler(
          servicer.GetKFlags,
          request_deserializer=rpc__pb2.GetKFlagsRequest.FromString,
          response_serializer=rpc__pb2.GetKFlagsReply.SerializeToString,
      ),
      'Capsule': grpc.unary_unary_rpc_method_handler(
          servicer.Capsule,
          request_deserializer=rpc__pb2.CapsuleRequest.FromString,
          response_serializer=rpc__pb2.CapsuleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nucypher.ReProxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
