# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='nucypher',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\trpc.proto\x12\x08nucypher\"*\n\x0e\x45ncryptRequest\x12\n\n\x02pk\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"0\n\x0c\x45ncryptReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61psule\x18\x02 \x01(\t\"d\n\x0e\x44\x65\x63ryptRequest\x12\n\n\x02sk\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61psule\x18\x03 \x01(\t\x12\x0b\n\x03\x63pk\x18\x04 \x01(\t\x12\x0b\n\x03ppk\x18\x05 \x01(\t\x12\r\n\x05\x66lags\x18\x06 \x03(\t\"\x1c\n\x0c\x44\x65\x63ryptReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"*\n\x10GetKFlagsRequest\x12\n\n\x02sk\x18\x01 \x01(\t\x12\n\n\x02pk\x18\x02 \x01(\t\"-\n\x0eGetKFlagsReply\x12\r\n\x05\x66lags\x18\x01 \x03(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"W\n\x0e\x43\x61psuleRequest\x12\x0f\n\x07\x63\x61psule\x18\x01 \x01(\t\x12\r\n\x05\x66lags\x18\x02 \x03(\t\x12\x0b\n\x03\x63pk\x18\x03 \x01(\t\x12\x0b\n\x03rpk\x18\x04 \x01(\t\x12\x0b\n\x03ppk\x18\x05 \x01(\t\"\x1c\n\x0c\x43\x61psuleReply\x12\x0c\n\x04text\x18\x01 \x01(\t2\x8b\x02\n\x07ReProxy\x12=\n\x07\x45ncrypt\x12\x18.nucypher.EncryptRequest\x1a\x16.nucypher.EncryptReply\"\x00\x12=\n\x07\x44\x65\x63rypt\x12\x18.nucypher.DecryptRequest\x1a\x16.nucypher.DecryptReply\"\x00\x12\x43\n\tGetKFlags\x12\x1a.nucypher.GetKFlagsRequest\x1a\x18.nucypher.GetKFlagsReply\"\x00\x12=\n\x07\x43\x61psule\x12\x18.nucypher.CapsuleRequest\x1a\x16.nucypher.CapsuleReply\"\x00\x62\x06proto3')
)




_ENCRYPTREQUEST = _descriptor.Descriptor(
  name='EncryptRequest',
  full_name='nucypher.EncryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pk', full_name='nucypher.EncryptRequest.pk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nucypher.EncryptRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=65,
)


_ENCRYPTREPLY = _descriptor.Descriptor(
  name='EncryptReply',
  full_name='nucypher.EncryptReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='nucypher.EncryptReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capsule', full_name='nucypher.EncryptReply.capsule', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=115,
)


_DECRYPTREQUEST = _descriptor.Descriptor(
  name='DecryptRequest',
  full_name='nucypher.DecryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sk', full_name='nucypher.DecryptRequest.sk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nucypher.DecryptRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capsule', full_name='nucypher.DecryptRequest.capsule', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpk', full_name='nucypher.DecryptRequest.cpk', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ppk', full_name='nucypher.DecryptRequest.ppk', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='nucypher.DecryptRequest.flags', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=217,
)


_DECRYPTREPLY = _descriptor.Descriptor(
  name='DecryptReply',
  full_name='nucypher.DecryptReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nucypher.DecryptReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=247,
)


_GETKFLAGSREQUEST = _descriptor.Descriptor(
  name='GetKFlagsRequest',
  full_name='nucypher.GetKFlagsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sk', full_name='nucypher.GetKFlagsRequest.sk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pk', full_name='nucypher.GetKFlagsRequest.pk', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=291,
)


_GETKFLAGSREPLY = _descriptor.Descriptor(
  name='GetKFlagsReply',
  full_name='nucypher.GetKFlagsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flags', full_name='nucypher.GetKFlagsReply.flags', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nucypher.GetKFlagsReply.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=338,
)


_CAPSULEREQUEST = _descriptor.Descriptor(
  name='CapsuleRequest',
  full_name='nucypher.CapsuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capsule', full_name='nucypher.CapsuleRequest.capsule', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='nucypher.CapsuleRequest.flags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpk', full_name='nucypher.CapsuleRequest.cpk', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpk', full_name='nucypher.CapsuleRequest.rpk', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ppk', full_name='nucypher.CapsuleRequest.ppk', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=427,
)


_CAPSULEREPLY = _descriptor.Descriptor(
  name='CapsuleReply',
  full_name='nucypher.CapsuleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nucypher.CapsuleReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=457,
)

DESCRIPTOR.message_types_by_name['EncryptRequest'] = _ENCRYPTREQUEST
DESCRIPTOR.message_types_by_name['EncryptReply'] = _ENCRYPTREPLY
DESCRIPTOR.message_types_by_name['DecryptRequest'] = _DECRYPTREQUEST
DESCRIPTOR.message_types_by_name['DecryptReply'] = _DECRYPTREPLY
DESCRIPTOR.message_types_by_name['GetKFlagsRequest'] = _GETKFLAGSREQUEST
DESCRIPTOR.message_types_by_name['GetKFlagsReply'] = _GETKFLAGSREPLY
DESCRIPTOR.message_types_by_name['CapsuleRequest'] = _CAPSULEREQUEST
DESCRIPTOR.message_types_by_name['CapsuleReply'] = _CAPSULEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncryptRequest = _reflection.GeneratedProtocolMessageType('EncryptRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.EncryptRequest)
  ))
_sym_db.RegisterMessage(EncryptRequest)

EncryptReply = _reflection.GeneratedProtocolMessageType('EncryptReply', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTREPLY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.EncryptReply)
  ))
_sym_db.RegisterMessage(EncryptReply)

DecryptRequest = _reflection.GeneratedProtocolMessageType('DecryptRequest', (_message.Message,), dict(
  DESCRIPTOR = _DECRYPTREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.DecryptRequest)
  ))
_sym_db.RegisterMessage(DecryptRequest)

DecryptReply = _reflection.GeneratedProtocolMessageType('DecryptReply', (_message.Message,), dict(
  DESCRIPTOR = _DECRYPTREPLY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.DecryptReply)
  ))
_sym_db.RegisterMessage(DecryptReply)

GetKFlagsRequest = _reflection.GeneratedProtocolMessageType('GetKFlagsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETKFLAGSREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.GetKFlagsRequest)
  ))
_sym_db.RegisterMessage(GetKFlagsRequest)

GetKFlagsReply = _reflection.GeneratedProtocolMessageType('GetKFlagsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETKFLAGSREPLY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.GetKFlagsReply)
  ))
_sym_db.RegisterMessage(GetKFlagsReply)

CapsuleRequest = _reflection.GeneratedProtocolMessageType('CapsuleRequest', (_message.Message,), dict(
  DESCRIPTOR = _CAPSULEREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.CapsuleRequest)
  ))
_sym_db.RegisterMessage(CapsuleRequest)

CapsuleReply = _reflection.GeneratedProtocolMessageType('CapsuleReply', (_message.Message,), dict(
  DESCRIPTOR = _CAPSULEREPLY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:nucypher.CapsuleReply)
  ))
_sym_db.RegisterMessage(CapsuleReply)



_REPROXY = _descriptor.ServiceDescriptor(
  name='ReProxy',
  full_name='nucypher.ReProxy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=460,
  serialized_end=727,
  methods=[
  _descriptor.MethodDescriptor(
    name='Encrypt',
    full_name='nucypher.ReProxy.Encrypt',
    index=0,
    containing_service=None,
    input_type=_ENCRYPTREQUEST,
    output_type=_ENCRYPTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Decrypt',
    full_name='nucypher.ReProxy.Decrypt',
    index=1,
    containing_service=None,
    input_type=_DECRYPTREQUEST,
    output_type=_DECRYPTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetKFlags',
    full_name='nucypher.ReProxy.GetKFlags',
    index=2,
    containing_service=None,
    input_type=_GETKFLAGSREQUEST,
    output_type=_GETKFLAGSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Capsule',
    full_name='nucypher.ReProxy.Capsule',
    index=3,
    containing_service=None,
    input_type=_CAPSULEREQUEST,
    output_type=_CAPSULEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPROXY)

DESCRIPTOR.services_by_name['ReProxy'] = _REPROXY

# @@protoc_insertion_point(module_scope)
